# Generated by Django 3.1 on 2020-11-12 08:51

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Calc_fees',
            fields=[
                ('fee_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('course_name', models.CharField(blank=True, max_length=20, null=True)),
                ('extra_fees', models.IntegerField(blank=True, default=0, null=True)),
                ('fee_details', models.TextField(blank=True, null=True)),
                ('total_fee', models.IntegerField()),
                ('payment', models.CharField(default='completed', max_length=20)),
                ('table_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Core_course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('course_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('fees', models.IntegerField()),
                ('table_status', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('total_hrs', models.IntegerField()),
                ('worked_hrs', models.IntegerField()),
                ('bonus', models.IntegerField(blank=True, null=True)),
                ('total_salary', models.IntegerField()),
                ('status', models.CharField(default='received', max_length=20)),
                ('table_status', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('skills', models.TextField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('wage', models.IntegerField()),
                ('table_status', models.IntegerField(blank=True, default=1, null=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('table_status', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
