from django.urls import path
from.import views

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
    path('login_admin', views.login_admin, name='login_admin'),
    path('login_staff', views.login_staff, name='login_staff'),
    path('login_student', views.login_student, name='login_student'),
    path('admin_register_page_fn', views.admin_register_page_fn, name='admin_register_page_fn'),
    path('admin_reg_fn', views.admin_reg_fn, name='admin_reg_fn'),
    path('admin_login_fn', views.admin_login_fn, name='admin_login_fn'),
    path('staffregistration', views.staffregistration, name='staffregistration'),
    path('staff_reg', views.staff_reg, name='staff_reg'),
    path('staff_login', views.staff_login, name='staff_login'),
    path('staff_logout', views.staff_logout, name='staff_logout'),
    path('view_all_staff', views.view_all_staff, name='view_all_staff'),
    path('staff_update/<int:staff_id>', views.staff_update),
    path('staff_update_submit', views.staff_update_submit),
    path('delete/<int:staff_id>', views.staff_delete),
    path('add_course_fn', views.add_course_fn, name='add_course_fn'),
    path('add_course_submit_fn', views.add_course_submit_fn),
    path('view_courses', views.view_courses, name='view_courses'),
    path('admin_logout_fn', views.admin_logout_fn, name='admin_logout_fn'),
    path('update_course/<int:course_id>', views.update_course, name='update_course'),
    path('update_course_submit_fn>', views.update_course_submit_fn, name='update_course_submit_fn'),
    path('course_delete/<int:course_id>', views.delete_course, name='delete_course'),
    path('student_register_page_fn', views.student_register_page_fn, name='student_register_page_fn'),
    path('student_reg_fn', views.student_reg_fn, name='student_reg_fn'),
    path('student_login_fn', views.student_login_fn, name='student_login_fn'),
    path('student_logout_fn', views.student_logout_fn, name='student_login_fn'),
    path('view_all_student_fn', views.view_all_student_fn, name='view_all_student_fn'),
    path('generate_fees', views.generate_fees, name='generate_fees'),
    path('generate_fees_save', views.generate_fees_save, name='generate_fees_save'),
    path('generate_salary', views.generate_salary, name='generate_salary'),
    path('generate_salary_save', views.generate_salary_save, name='generate_salary_save'),
    path('contact', views.contact, name='contact'),
]
